influxdb:
  image: influxdb:latest
  container_name: influxdb
  ports:
    - "8083:8083"
    - "8086:8086"
    - "8090:8090"
    - "2003:2003"
  env_file:
    - './influxdb/env.influxdb'
  volumes:
    - ./influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro
    - ./influxdb:/data01

grafana:
  image: grafana/grafana:latest
  container_name: grafana
  ports:
    - "3000:3000"
  links:
    - influxdb

nginx:
  image: sportebois/nginx-rate-limit-sandbox
  container_name: nginx
  ports:
    - "8080:80"
  volumes:
   - ./nginx/conf.d:/etc/nginx/conf.d
   - ./nginx/html:/etc/nginx/html
